// ============================================================
// LEARN TF // ENGLISH & ANSWERING SKILLS
// ============================================================

const englishQuizzes = {

// ---------- WRITING SKILLS ----------
"Eng 1.1: Sentence Structures": [
  {q:"What is a <b>simple sentence</b>?", answer:"One independent clause (one subject + one verb)", accepts:["one independent clause","one clause","subject and verb","one subject one verb"], hint:"The most basic sentence type.", explanation:"A simple sentence has ONE independent clause: subject + verb + (object). E.g. 'The cat sat on the mat.'"},
  {q:"What is a <b>compound sentence</b>?", answer:"Two independent clauses joined by a conjunction (and, but, or)", accepts:["two independent clauses joined by a conjunction","two clauses joined by and but or","two independent clauses"], hint:"Think FANBOYS: for, and, nor, but, or, yet, so.", explanation:"A compound sentence joins two independent clauses with a coordinating conjunction (FANBOYS). E.g. 'I studied hard, but I still failed.'"},
  {q:"What is a <b>complex sentence</b>?", answer:"An independent clause + a dependent clause", accepts:["independent clause and dependent clause","main clause and subordinate clause","one independent one dependent"], hint:"One clause can stand alone, the other can't.", explanation:"A complex sentence has one main clause and at least one subordinate (dependent) clause. E.g. 'Although it rained, we went outside.'"},
  {q:"Identify the type: 'She ran to the store.'", answer:"Simple", accepts:["simple","simple sentence"], hint:"How many clauses? Is there a conjunction or dependent clause?", explanation:"One subject (she), one verb (ran), no conjunction or dependent clause → simple sentence."},
  {q:"Identify the type: 'I wanted to go, but it was too late.'", answer:"Compound", accepts:["compound","compound sentence"], hint:"Two complete thoughts joined by 'but'.", explanation:"'I wanted to go' and 'it was too late' are both independent clauses joined by 'but' → compound."},
  {q:"Identify the type: 'Because he was tired, he went to bed early.'", answer:"Complex", accepts:["complex","complex sentence"], hint:"'Because he was tired' cannot stand alone.", explanation:"'Because he was tired' is a dependent clause; 'he went to bed early' is independent → complex."},
  {q:"What are the FANBOYS conjunctions?", answer:"For, And, Nor, But, Or, Yet, So", accepts:["for and nor but or yet so","fanboys"], hint:"The acronym spells FANBOYS.", explanation:"FANBOYS = For, And, Nor, But, Or, Yet, So. These join independent clauses in compound sentences."},
  {q:"Fix this run-on: 'I like pizza I eat it every day.'", answer:"I like pizza, and I eat it every day.", accepts:["i like pizza, and i eat it every day","i like pizza and i eat it every day","i like pizza. i eat it every day"], hint:"Add a conjunction or split into two sentences.", explanation:"Run-on fixed by adding a comma + conjunction: 'I like pizza, and I eat it every day.' Or use a full stop."},
  {q:"What is a sentence fragment?", answer:"An incomplete sentence that is missing a subject, verb, or complete thought", accepts:["incomplete sentence","missing subject or verb","not a complete thought"], hint:"It looks like a sentence but something is missing.", explanation:"A fragment is missing a subject, verb, or doesn't express a complete thought. E.g. 'Running down the street.' (Who? What happened?)"},
  {q:"Is this a fragment? 'When the bell rang.'", answer:"Yes", accepts:["yes","y","true"], hint:"Can it stand alone as a complete thought?", explanation:"Yes — 'When the bell rang' is a dependent clause. It needs a main clause: 'When the bell rang, we left.'"}
],

"Eng 1.2: Transition Words": [
  {q:"Give a transition word for <b>adding</b> information.", answer:"Furthermore", accepts:["furthermore","moreover","in addition","additionally","also"], hint:"You're building on what you already said.", explanation:"Adding: furthermore, moreover, in addition, additionally, also, besides."},
  {q:"Give a transition word for <b>contrasting</b>.", answer:"However", accepts:["however","whereas","although","nevertheless","on the other hand","but"], hint:"You're showing the other side.", explanation:"Contrasting: however, whereas, although, nevertheless, on the other hand, conversely."},
  {q:"Give a transition word for <b>cause</b>.", answer:"Because", accepts:["because","since","as","due to"], hint:"You're explaining WHY something happens.", explanation:"Cause: because, since, as, due to, owing to."},
  {q:"Give a transition word for <b>effect/result</b>.", answer:"Therefore", accepts:["therefore","consequently","hence","thus","as a result"], hint:"You're showing WHAT HAPPENED as a result.", explanation:"Effect: therefore, consequently, hence, thus, as a result."},
  {q:"Give a transition word for <b>giving examples</b>.", answer:"For example", accepts:["for example","for instance","such as"], hint:"You're illustrating your point.", explanation:"Examples: for example, for instance, such as, namely, to illustrate."},
  {q:"Give a transition word for <b>concluding</b>.", answer:"In conclusion", accepts:["in conclusion","overall","to summarize","in summary","to conclude"], hint:"You're wrapping up.", explanation:"Concluding: in conclusion, overall, to summarize, in summary, ultimately."},
  {q:"Which is better? 'It rained. We still went out.' or 'Although it rained, we still went out.'", answer:"The second (uses a transition)", accepts:["second","the second","although it rained"], hint:"Which one shows the relationship between the ideas?", explanation:"The second is better because 'although' shows the contrast between the rain and going out. It flows better."},
  {q:"Fill in: 'The experiment failed; ______, we learned from it.'", answer:"nevertheless", accepts:["nevertheless","however","nonetheless"], hint:"You need a word that means 'despite that'.", explanation:"'Nevertheless' or 'however' shows contrast — the failure didn't stop the learning."},
  {q:"Fill in: 'She studied hard. ______, she passed the exam.'", answer:"Therefore", accepts:["therefore","consequently","as a result","thus"], hint:"Studying caused the passing.", explanation:"'Therefore' shows the cause-effect: studying → passing."},
  {q:"Is 'Also' a strong academic transition word?", answer:"No (use 'Furthermore' or 'Moreover' instead)", accepts:["no","false","n"], hint:"Think formal vs informal.", explanation:"'Also' is acceptable but weak. In formal writing, prefer 'furthermore', 'moreover', or 'in addition'."}
],

"Eng 1.3: Common Grammar Errors": [
  {q:"Fix: 'The team are winning.'", answer:"The team is winning.", accepts:["the team is winning"], hint:"'Team' is a collective noun — singular in British English.", explanation:"Collective nouns (team, class, group) are usually treated as singular: 'The team IS winning.'"},
  {q:"Fix: 'Everyone should bring their book.'", answer:"Everyone should bring his or her book.", accepts:["everyone should bring his or her book","everyone should bring their books"], hint:"'Everyone' is singular — technically needs a singular pronoun.", explanation:"Strictly: 'his or her book.' In modern English, singular 'their' is increasingly accepted, but exams may want the formal version."},
  {q:"Fix: 'Me and him went to the shop.'", answer:"He and I went to the shop.", accepts:["he and i went to the shop"], hint:"Remove 'and him' — would you say 'me went to the shop'?", explanation:"Subject pronouns: I, he, she, we, they. 'He and I went to the shop.' (Never 'me and him' as subject.)"},
  {q:"Fix: 'I could of done better.'", answer:"I could have done better.", accepts:["i could have done better","i could've done better"], hint:"It's 'could HAVE', not 'could of'.", explanation:"'Could of' is ALWAYS wrong. It sounds like 'could've' (could have) when spoken fast, but 'of' is not a verb."},
  {q:"Fix: 'Their going to they're house over there.'", answer:"They're going to their house over there.", accepts:["they're going to their house over there"], hint:"They're = they are. Their = possession. There = place.", explanation:"They're (they are) going to their (belonging to them) house over there (that place)."},
  {q:"Fix: 'The dog wagged it's tail.'", answer:"The dog wagged its tail.", accepts:["the dog wagged its tail"], hint:"it's = it is. its = belonging to it.", explanation:"'Its' (no apostrophe) = possessive. 'It's' = it is. The tail belongs to the dog, so 'its tail'."},
  {q:"Fix: 'I done my homework yesterday.'", answer:"I did my homework yesterday.", accepts:["i did my homework yesterday"], hint:"'Done' needs a helper verb (have/has). Simple past = 'did'.", explanation:"Simple past: 'I did.' Present perfect: 'I have done.' Never 'I done' on its own."},
  {q:"Fix: 'She is more taller than me.'", answer:"She is taller than me.", accepts:["she is taller than me","she is taller than i"], hint:"Don't use 'more' with '-er' adjectives.", explanation:"Either 'taller' OR 'more tall' — never both. Short adjectives use -er: taller, faster, bigger."},
  {q:"'Less' or 'fewer'? '_____ people came today.'", answer:"Fewer", accepts:["fewer"], hint:"Can you count people?", explanation:"Fewer = countable (fewer people, fewer books). Less = uncountable (less water, less time)."},
  {q:"Fix: 'Between you and I, this is wrong.'", answer:"Between you and me, this is wrong.", accepts:["between you and me"], hint:"After prepositions (between, for, to), use object pronouns.", explanation:"'Between' is a preposition → needs object pronoun: me, him, her, us. 'Between you and ME.'"}
],

"Eng 1.4: Formal vs Informal": [
  {q:"Replace informally: 'kids' → formal?", answer:"children", accepts:["children","young people"], hint:"What would you write in an essay?", explanation:"kids → children / young people (in formal writing)."},
  {q:"Replace: 'a lot of' → formal?", answer:"many / much / numerous", accepts:["many","much","numerous","a great deal of","a large number of"], hint:"'A lot' is too casual for essays.", explanation:"a lot of → many (countable), much (uncountable), numerous, a significant number of."},
  {q:"Replace: 'get' → formal? (in 'get a job')", answer:"obtain", accepts:["obtain","secure","acquire"], hint:"Think of a more precise word.", explanation:"get → obtain, acquire, secure, receive (depending on context)."},
  {q:"Should you use contractions (can't, won't, isn't) in formal writing?", answer:"No", accepts:["no","n","false"], hint:"Contractions are informal.", explanation:"Avoid contractions in formal/academic writing. Write 'cannot', 'will not', 'is not'."},
  {q:"Replace: 'thing' → formal? (in 'an important thing')", answer:"factor / aspect / matter", accepts:["factor","aspect","matter","issue","element","consideration"], hint:"'Thing' is vague — be specific.", explanation:"thing → factor, aspect, matter, issue, element. Always try to be specific about WHAT thing."},
  {q:"Replace: 'good' → stronger word?", answer:"effective / beneficial / excellent", accepts:["effective","beneficial","excellent","advantageous","commendable"], hint:"'Good' is generic. What kind of good?", explanation:"good → effective, beneficial, excellent, advantageous, commendable (pick one that fits the context)."},
  {q:"Replace: 'bad' → stronger word?", answer:"detrimental / harmful / inadequate", accepts:["detrimental","harmful","inadequate","adverse","negative"], hint:"What kind of bad?", explanation:"bad → detrimental, harmful, inadequate, adverse, problematic."},
  {q:"Replace: 'big' → stronger word?", answer:"significant / substantial / considerable", accepts:["significant","substantial","considerable","major","enormous"], hint:"Is it big in size, importance, or amount?", explanation:"big → significant (importance), substantial (amount), considerable, major, vast."},
  {q:"Is 'In my opinion, I think...' good writing?", answer:"No (redundant — pick one)", accepts:["no","false","n","redundant"], hint:"'In my opinion' already means 'I think'.", explanation:"Redundant — say EITHER 'In my opinion,...' OR 'I think...' — not both."},
  {q:"Replace: 'stuff' → formal?", answer:"material / items / content / aspects", accepts:["material","items","content","aspects","elements","matters"], hint:"What stuff? Be specific.", explanation:"'Stuff' is vague and informal. Replace with the specific noun: materials, items, content, aspects."}
],

// ---------- ANSWERING SKILLS ----------
"Eng 2.1: Command Words": [
  {q:"What does the command word <b>State</b> mean?", answer:"Give the answer directly (no explanation needed)", accepts:["give the answer directly","just give the answer","write the answer","give it directly"], hint:"Short and direct.", explanation:"'State' = give a brief, direct answer. No explanation or description needed. Just the fact."},
  {q:"What does <b>Describe</b> mean?", answer:"Say what happens or what something is like", accepts:["say what happens","what it is like","give details of what happens","write what happens"], hint:"Paint a picture with words — what do you see/observe?", explanation:"'Describe' = say what happens, what you observe, what it looks like. No need to explain WHY."},
  {q:"What does <b>Explain</b> mean?", answer:"Say what happens AND why/how", accepts:["what and why","say what happens and why","what happens and how","give reason"], hint:"Describe + give a reason.", explanation:"'Explain' = state what happens + give the reason (because...). You need the WHY or HOW, not just the WHAT."},
  {q:"What does <b>Compare</b> mean?", answer:"Give similarities and/or differences", accepts:["similarities and differences","give similarities and differences","similarities or differences"], hint:"Use words like 'whereas', 'both', 'unlike'.", explanation:"'Compare' = identify what's similar AND what's different. Use 'A is... whereas B is...' structure."},
  {q:"What does <b>Calculate</b> mean?", answer:"Show formula, substitute, solve, give unit", accepts:["show working","formula then substitute","show formula substitute answer unit"], hint:"Formula → numbers in → answer + unit.", explanation:"'Calculate' = write the formula, substitute values, show the calculation, give the answer WITH the correct unit."},
  {q:"What does <b>Suggest</b> mean?", answer:"Give a reasonable possible answer (there may be multiple valid answers)", accepts:["give a reasonable answer","possible answer","a plausible answer"], hint:"You're not expected to know for certain — just make a sensible guess.", explanation:"'Suggest' = propose a reasonable answer. The marker accepts multiple valid responses. Use your knowledge to give a sensible answer."},
  {q:"What does <b>Justify</b> mean?", answer:"Give your answer AND provide evidence/reasoning to support it", accepts:["give answer and evidence","answer with reasoning","support with evidence"], hint:"Answer + proof.", explanation:"'Justify' = state your answer + give evidence or reasoning that supports it. 'I chose X because...'"},
  {q:"What does <b>Evaluate</b> mean?", answer:"Give advantages AND disadvantages, then a conclusion", accepts:["advantages and disadvantages","pros and cons and conclusion","weigh up both sides"], hint:"Both sides + your judgement.", explanation:"'Evaluate' = discuss pros and cons / strengths and weaknesses, then give your overall judgement or conclusion."},
  {q:"What does <b>Define</b> mean?", answer:"Give the precise meaning of a term", accepts:["give the meaning","precise meaning","state the meaning","definition"], hint:"Like a dictionary entry.", explanation:"'Define' = state exactly what the term means, using precise scientific/technical language."},
  {q:"What does <b>Name</b> mean?", answer:"Give the correct term (one word or short phrase)", accepts:["give the correct term","one word answer","name it","the term"], hint:"Even shorter than 'state' — usually just a word or name.", explanation:"'Name' = write the specific term, label, or name. Usually one word or a short phrase. No explanation needed."}
],

"Eng 2.2: How to Structure Answers": [
  {q:"What structure should an 'Explain' answer follow?", answer:"Point → Because → Explanation", accepts:["point because explanation","what because why","point then because then explanation"], hint:"What happens + because + why.", explanation:"State WHAT happens → 'because' → explain WHY/HOW. E.g. 'The current increases because the resistance decreases, allowing more charge to flow per second.'"},
  {q:"What does PEEL stand for?", answer:"Point, Evidence, Explanation, Link", accepts:["point evidence explanation link","point, evidence, explanation, link"], hint:"A paragraph structure for essays.", explanation:"P = Point (topic sentence), E = Evidence/Example, E = Explanation (how it supports your point), L = Link (back to the question or to next point)."},
  {q:"How should you answer a 'Compare' question?", answer:"A is ___ whereas B is ___", accepts:["a is whereas b is","use whereas","compare directly"], hint:"Put both things in the SAME sentence.", explanation:"Use 'A is... whereas B is...' or 'Both A and B...' Don't write two separate paragraphs about each — compare them directly."},
  {q:"How should you show working in a calculation?", answer:"Formula → Substitution → Answer + Unit", accepts:["formula substitution answer unit","formula then substitute then answer"], hint:"Three lines minimum.", explanation:"Line 1: V = IR (formula). Line 2: V = 2 × 4 (substitution). Line 3: V = 8 V (answer with unit). Even if you get the wrong number, you get method marks for lines 1 and 2."},
  {q:"What's wrong with: 'Because it saves time.'?", answer:"It's a sentence fragment (no main clause)", accepts:["fragment","sentence fragment","incomplete sentence","no main clause"], hint:"Can it stand alone as a complete answer?", explanation:"This is a fragment — it only has a dependent clause. Write: 'It is beneficial because it saves time.' (full sentence with a main clause)."},
  {q:"Rewrite as a full sentence: 'Because the resistance is higher.'", answer:"The current decreases because the resistance is higher.", accepts:["the current decreases because the resistance is higher","it decreases because the resistance is higher"], hint:"Add a main clause before 'because'.", explanation:"Add the main point first: 'The current decreases because the resistance is higher.' Now it's a complete answer."},
  {q:"In a 'Why' question, what structure should you use?", answer:"Answer → because → reason → result", accepts:["answer because reason","answer then because then reason"], hint:"State what happens, then explain with 'because'.", explanation:"'Why does the lamp get dimmer?' → 'The lamp gets dimmer because the current decreases, so less energy is transferred per second.'"},
  {q:"What's wrong with copying a whole sentence from the passage in comprehension?", answer:"You should paraphrase (put it in your own words)", accepts:["should paraphrase","put in own words","don't copy","rephrase it"], hint:"The marker wants to see YOU understand it.", explanation:"Lifting = copying. Paraphrase = put it in your own words. Examiners want to see that you UNDERSTAND the text, not that you can copy it."},
  {q:"For a 2-mark 'Explain' question, how many points do you need?", answer:"1 point with a developed explanation (or 2 brief points)", accepts:["1 point with explanation","one developed point","2 brief points"], hint:"Each mark = either a new point or a deeper explanation of the same point.", explanation:"Usually: 1 mark for identifying WHAT + 1 mark for explaining WHY. Or sometimes 2 separate points, 1 mark each."},
  {q:"What should you always check your answer has at the end?", answer:"Units (for calculations) or a full sentence (for written answers)", accepts:["units","full sentence","unit","complete sentence"], hint:"The most common way to lose easy marks.", explanation:"Calculations: always write the unit (V, A, Ω, etc.). Written answers: always write in complete sentences. These are free marks that students throw away."}
],

"Eng 2.3: Summary Writing": [
  {q:"What is the FIRST step in summary writing?", answer:"Read the passage and identify the main points", accepts:["identify main points","read and find main points","find the key points"], hint:"Before you write anything, you need to know WHAT to include.", explanation:"Step 1: Read carefully and underline/highlight the main points. Ignore examples, descriptions, and repetition."},
  {q:"Should you include examples and details in a summary?", answer:"No — only main points", accepts:["no","false","n","only main points"], hint:"A summary is SHORT. Cut the fat.", explanation:"No. A summary removes examples, anecdotes, descriptions, and repetition. Keep only the core ideas."},
  {q:"Should you copy sentences directly from the text?", answer:"No — paraphrase (use your own words)", accepts:["no","paraphrase","own words","rephrase"], hint:"The examiner is testing YOUR ability to rephrase.", explanation:"Never copy directly. Paraphrase = rewrite in your own words while keeping the same meaning. This shows comprehension."},
  {q:"What should you do if two paragraphs make similar points?", answer:"Combine them into one point", accepts:["combine them","merge them","write as one point"], hint:"Don't repeat yourself.", explanation:"If the text says the same thing twice in different words, combine them into a single concise point in your summary."},
  {q:"Should you add your own opinions in a summary?", answer:"No", accepts:["no","n","false","never"], hint:"A summary reports what the TEXT says.", explanation:"Never add personal opinions, interpretations, or new information. A summary only contains what the original text says."},
  {q:"How do you stay within the word limit?", answer:"Use concise language, cut unnecessary words, combine points", accepts:["be concise","cut unnecessary words","use fewer words","shorten sentences"], hint:"Every word must earn its place.", explanation:"Replace phrases with single words ('due to the fact that' → 'because'). Cut filler words. Merge related points."},
  {q:"Replace with fewer words: 'due to the fact that'", answer:"because", accepts:["because","since","as"], hint:"4 words → 1 word.", explanation:"'Due to the fact that' = 'because'. Always look for shorter ways to say the same thing in summaries."},
  {q:"Replace with fewer words: 'in order to'", answer:"to", accepts:["to"], hint:"3 words → 1 word.", explanation:"'In order to' = 'to'. E.g. 'He ran in order to catch the bus' → 'He ran to catch the bus.'"},
  {q:"What tense should a summary usually be in?", answer:"The same tense as the original text (usually present)", accepts:["same as original","present tense","same tense"], hint:"Match the source.", explanation:"Use the same tense as the original passage. If it's written in present tense, summarize in present tense. Be consistent."},
  {q:"How many words is a typical summary at Sec 2 level?", answer:"About 80-100 words (or as specified)", accepts:["80","100","80-100","80 to 100"], hint:"Check the question — it usually tells you.", explanation:"Typically 80-100 words, but ALWAYS check what the question asks for. Going over the limit loses marks."}
]

};
